### PR TITLE
Starting UI for NFT transfer functionality

### PR DESCRIPTION
**Pull request by roger-rangel**
Starting its implementation on the User Settings Page. This functionality will be transferred to other parts of our App on the 3rd Milestone once I refactor the Frontend and migrate the code to Next Js for better readability and performance.

### CODE REVIEW

**Comment by Szegoo** [comment]
@roger-rangel We could probably rename the `/usersettings` page to just `/user` or `/profile` page. I think it would make more sense. And also update the icon that routes to this page so that it matches the new name.

**Comment by roger-rangel** [comment]
Once I finisht the radio buttons for choosing NFT or Soulbound today I will swtich it to Profile Page  as well as the icon 👍

**Comment by roger-rangel** [comment]
Screenshot 2023-03-04 at 6 01 44 PM

**Comment by roger-rangel** [comment]
The conflicts that appear above are caused because I changed the name of the directory of UserSettings -> ProfilePage, which affect both the index.js file and all the files pertaining to UserMenu.  Routing to the profile was changed from /usersettings -> /profile.

**Comment by Szegoo** [comment]
The UI is looking good, once we resolve the conflict we can probably merge this and later create a separate PR for the transfer functionality UI. Or do you want to keep working on this branch?

**Comment by roger-rangel** [comment]
> The UI is looking good, once we resolve the conflict we can probably merge this and later create a separate PR for the transfer functionality UI. Or do you want to keep working on this branch?

Sure we can resolve the conflict and merge it afterwards. What should I call the new seperate branch?

**Comment by Szegoo** [comment]
Resolved the conflicts and merged.

> What should I call the new seperate branch?\

It is up to you.. transfer-modal, or something similar.

**Pull request merged**
